#!/bin/bash --

sqlite3 -batch distributors.db <<"EOF"
UPDATE Films SET Distributor = "Janus Films" WHERE Title = "La Chambre" AND Year = "1972";
UPDATE Films SET Distributor = "Janus Films" WHERE Title = "Hôtel Monterey" AND Year = "1972";
UPDATE Films SET Distributor = "Janus Films" WHERE Title = "I, You, He, She" AND Year = "1974";
UPDATE Films SET Distributor = "Janus Films" WHERE Title = "Jeanne Dielman, 23 Commerce Quay, 1080 Brussels" AND Year = "1975";
UPDATE Films SET Distributor = "Janus Films" WHERE Title = "News From Home" AND Year = "1977";
UPDATE Films SET Distributor = "Janus Films" WHERE Title = "Anna’s Meetings" AND Year = "1978";
UPDATE Films SET Distributor = "Janus Films" WHERE Title = "Liv & Ingmar" AND Year = "2012";
UPDATE Films SET Distributor = "Janus Films" WHERE Title = "L'Avventura" AND Year = "1960";
UPDATE Films SET Distributor = "Janus Films" WHERE Title = "L'Eclisse" AND Year = "1962";
UPDATE Films SET Distributor = "Janus Films" WHERE Title = "Identification Of A Woman" AND Year = "1982";
UPDATE Films SET Distributor = "Janus Films" WHERE Title = "Red Desert" AND Year = "1964";
UPDATE Films SET Distributor = "Janus Films" WHERE Title = "The Browning Version" AND Year = "1951";
UPDATE Films SET Distributor = "Janus Films" WHERE Title = "Pygmalion" AND Year = "1938";
UPDATE Films SET Distributor = "Janus Films" WHERE Title = "Babette’s Feast" AND Year = "1987";
UPDATE Films SET Distributor = "Janus Films" WHERE Title = "Death of a Cyclist" AND Year = "1955";
UPDATE Films SET Distributor = "Janus Films" WHERE Title = "Eating Raoul" AND Year = "1982";
UPDATE Films SET Distributor = "Janus Films" WHERE Title = "Casque D'Or" AND Year = "1952";
UPDATE Films SET Distributor = "Janus Films" WHERE Title = "Fists In The Pocket" AND Year = "1965";
UPDATE Films SET Distributor = "Janus Films" WHERE Title = "Man Bites Dog" AND Year = "1992";
UPDATE Films SET Distributor = "Janus Films" WHERE Title = "The Thief Of Bagdad" AND Year = "1940";
UPDATE Films SET Distributor = "Janus Films" WHERE Title = "Autumn Sonata" AND Year = "1978";
UPDATE Films SET Distributor = "Janus Films" WHERE Title = "Cries And Whispers" AND Year = "1972";
UPDATE Films SET Distributor = "Janus Films" WHERE Title = "Crisis" AND Year = "1946";
UPDATE Films SET Distributor = "Janus Films" WHERE Title = "The Devil’s Eye" AND Year = "1960";
UPDATE Films SET Distributor = "Janus Films" WHERE Title = "Dreams" AND Year = "1955";
UPDATE Films SET Distributor = "Janus Films" WHERE Title = "Fanny And Alexander" AND Year = "1982";
UPDATE Films SET Distributor = "Janus Films" WHERE Title = "A Lesson In Love" AND Year = "1954";
UPDATE Films SET Distributor = "Janus Films" WHERE Title = "The Magic Flute" AND Year = "1975";
UPDATE Films SET Distributor = "Janus Films" WHERE Title = "The Magician" AND Year = "1958";
UPDATE Films SET Distributor = "Janus Films" WHERE Title = "Persona" AND Year = "1966";
UPDATE Films SET Distributor = "Janus Films" WHERE Title = "Port Of Call" AND Year = "1948";
UPDATE Films SET Distributor = "Janus Films" WHERE Title = "Rite" AND Year = "1969";
UPDATE Films SET Distributor = "Janus Films" WHERE Title = "Sawdust And Tinsel" AND Year = "1953";
UPDATE Films SET Distributor = "Janus Films" WHERE Title = "Scenes From A Marriage" AND Year = "1973";
UPDATE Films SET Distributor = "Janus Films" WHERE Title = "Secrets Of Women" AND Year = "1952";
UPDATE Films SET Distributor = "Janus Films" WHERE Title = "The Seventh Seal" AND Year = "1957";
UPDATE Films SET Distributor = "Janus Films" WHERE Title = "The Silence" AND Year = "1963";
UPDATE Films SET Distributor = "Janus Films" WHERE Title = "Smiles Of A Summer Night" AND Year = "1955";
UPDATE Films SET Distributor = "Janus Films" WHERE Title = "Summer Interlude" AND Year = "1951";
UPDATE Films SET Distributor = "Janus Films" WHERE Title = "Summer With Monika" AND Year = "1953";
UPDATE Films SET Distributor = "Janus Films" WHERE Title = "Thirst" AND Year = "1949";
UPDATE Films SET Distributor = "Janus Films" WHERE Title = "Through A Glass Darkly" AND Year = "1961";
UPDATE Films SET Distributor = "Janus Films" WHERE Title = "To Joy" AND Year = "1950";
UPDATE Films SET Distributor = "Janus Films" WHERE Title = "The Virgin Spring" AND Year = "1960";
UPDATE Films SET Distributor = "Janus Films" WHERE Title = "Wild Strawberries" AND Year = "1957";
UPDATE Films SET Distributor = "Janus Films" WHERE Title = "Winter Light" AND Year = "1963";
UPDATE Films SET Distributor = "Janus Films" WHERE Title = "Les Misérables" AND Year = "1934";
UPDATE Films SET Distributor = "Janus Films" WHERE Title = "Wooden Crosses" AND Year = "1932";
UPDATE Films SET Distributor = "Janus Films" WHERE Title = "The Grim Reaper" AND Year = "1962";
UPDATE Films SET Distributor = "Janus Films" WHERE Title = "The Ladies of the Bois de Boulogne" AND Year = "1945";
UPDATE Films SET Distributor = "Janus Films" WHERE Title = "A Man Escaped or: The Wind Bloweth Where It Listeth" AND Year = "1956";
UPDATE Films SET Distributor = "Janus Films" WHERE Title = "Pickpocket" AND Year = "1959";
UPDATE Films SET Distributor = "Janus Films" WHERE Title = "Lord of the Flies" AND Year = "1963";
UPDATE Films SET Distributor = "Janus Films" WHERE Title = "Belle de Jour" AND Year = "1967";
UPDATE Films SET Distributor = "Janus Films" WHERE Title = "The Exterminating Angel" AND Year = "1962";
UPDATE Films SET Distributor = "Janus Films" WHERE Title = "Simon of the Desert" AND Year = "1965";
UPDATE Films SET Distributor = "Janus Films" WHERE Title = "Viridiana" AND Year = "1961";
UPDATE Films SET Distributor = "Janus Films" WHERE Title = "An Angel at My Table" AND Year = "1990";
UPDATE Films SET Distributor = "Janus Films" WHERE Title = "Sweetie" AND Year = "1989";
UPDATE Films SET Distributor = "Janus Films" WHERE Title = "Black Orpheus" AND Year = "1959";
UPDATE Films SET Distributor = "Janus Films" WHERE Title = "Children of Paradise" AND Year = "1945";
UPDATE Films SET Distributor = "Janus Films" WHERE Title = "Les Visiteurs du Soir" AND Year = "1942";
UPDATE Films SET Distributor = "Janus Films" WHERE Title = "The Night Porter" AND Year = "1974";
UPDATE Films SET Distributor = "Janus Films" WHERE Title = "The King of Kings" AND Year = "1927";
UPDATE Films SET Distributor = "Janus Films" WHERE Title = "Le Beau Serge" AND Year = "1958";
UPDATE Films SET Distributor = "Janus Films" WHERE Title = "Les Cousins" AND Year = "1959";
UPDATE Films SET Distributor = "Janus Films" WHERE Title = "The Circus" AND Year = "1928";
UPDATE Films SET Distributor = "Janus Films" WHERE Title = "City Lights" AND Year = "1931";
UPDATE Films SET Distributor = "Janus Films" WHERE Title = "A Day's Pleasure" AND Year = "1919";
UPDATE Films SET Distributor = "Janus Films" WHERE Title = "A Dog's Life" AND Year = "1918";
UPDATE Films SET Distributor = "Janus Films" WHERE Title = "The Gold Rush" AND Year = "1925";
UPDATE Films SET Distributor = "Janus Films" WHERE Title = "The Dictator" AND Year = "1940";
UPDATE Films SET Distributor = "Janus Films" WHERE Title = "The Idle Class" AND Year = "1921";
UPDATE Films SET Distributor = "Janus Films" WHERE Title = "The Kid" AND Year = "1921";
UPDATE Films SET Distributor = "Janus Films" WHERE Title = "A King in New York" AND Year = "1957";
UPDATE Films SET Distributor = "Janus Films" WHERE Title = "Limelight" AND Year = "1952";
UPDATE Films SET Distributor = "Janus Films" WHERE Title = "Modern Times" AND Year = "1936";
UPDATE Films SET Distributor = "Janus Films" WHERE Title = "Pay Day" AND Year = "1922";
UPDATE Films SET Distributor = "Janus Films" WHERE Title = "The Pilgrim" AND Year = "1923";
UPDATE Films SET Distributor = "Janus Films" WHERE Title = "Shoulder Arms" AND Year = "1918";
UPDATE Films SET Distributor = "Janus Films" WHERE Title = "A Woman of Paris: A Drama of Fate" AND Year = "1923";
UPDATE Films SET Distributor = "Janus Films" WHERE Title = "Häxan: Witchcraft Through the Ages" AND Year = "1922";
UPDATE Films SET Distributor = "Janus Films" WHERE Title = "Daisies" AND Year = "1966";
UPDATE Films SET Distributor = "Janus Films" WHERE Title = "À Nous la Liberté" AND Year = "1931";
UPDATE Films SET Distributor = "Janus Films" WHERE Title = "Le Million" AND Year = "1931";
UPDATE Films SET Distributor = "Janus Films" WHERE Title = "Under the Roofs of Paris" AND Year = "1930";
UPDATE Films SET Distributor = "Janus Films" WHERE Title = "Plein Soleil" AND Year = "1960";
UPDATE Films SET Distributor = "Janus Films" WHERE Title = "Watch Your Left" AND Year = "1936";
UPDATE Films SET Distributor = "Janus Films" WHERE Title = "Diabolique" AND Year = "1955";
UPDATE Films SET Distributor = "Janus Films" WHERE Title = "The Wages of Fear" AND Year = "1953";
UPDATE Films SET Distributor = "Janus Films" WHERE Title = "La Belle et la Bête" AND Year = "1946";
UPDATE Films SET Distributor = "Janus Films" WHERE Title = "Orpheus" AND Year = "1950";
UPDATE Films SET Distributor = "Janus Films" WHERE Title = "Overlord" AND Year = "1975";
UPDATE Films SET Distributor = "Janus Films" WHERE Title = "Colossal Youth" AND Year = "2006";
UPDATE Films SET Distributor = "Janus Films" WHERE Title = "In Vanda’s Room" AND Year = "2000";
UPDATE Films SET Distributor = "Janus Films" WHERE Title = "Ossos" AND Year = "1997";
UPDATE Films SET Distributor = "Janus Films" WHERE Title = "The Rise of Catherine the Great" AND Year = "1934";
UPDATE Films SET Distributor = "Janus Films" WHERE Title = "La Promesse" AND Year = "1996";
UPDATE Films SET Distributor = "Janus Films" WHERE Title = "Brute Force" AND Year = "1947";
UPDATE Films SET Distributor = "Janus Films" WHERE Title = "The Naked City" AND Year = "1948";
UPDATE Films SET Distributor = "Janus Films" WHERE Title = "Sisters" AND Year = "1973";
UPDATE Films SET Distributor = "Janus Films" WHERE Title = "The Children Are Watching Us" AND Year = "1944";
UPDATE Films SET Distributor = "Janus Films" WHERE Title = "The League of Gentlemen" AND Year = "1960";
UPDATE Films SET Distributor = "Janus Films" WHERE Title = "Victim" AND Year = "1961";
UPDATE Films SET Distributor = "Janus Films" WHERE Title = "Bay of the Angels" AND Year = "1963";
UPDATE Films SET Distributor = "Janus Films" WHERE Title = "Une chambre en ville" AND Year = "1982";
UPDATE Films SET Distributor = "Janus Films" WHERE Title = "Donkey Skin" AND Year = "1970";
UPDATE Films SET Distributor = "Janus Films" WHERE Title = "Lola" AND Year = "1961";
UPDATE Films SET Distributor = "Janus Films" WHERE Title = "L'événement le plus important depuis que l'homme a marché sur la lune" AND Year = "1973";
UPDATE Films SET Distributor = "Janus Films" WHERE Title = "The Umbrellas of Cherbourg" AND Year = "1964";
UPDATE Films SET Distributor = "Janus Films" WHERE Title = "The Devil and Daniel Webster" AND Year = "1941";
UPDATE Films SET Distributor = "Janus Films" WHERE Title = "Babo 73" AND Year = "1964";
UPDATE Films SET Distributor = "Janus Films" WHERE Title = "Chafed Elbows" AND Year = "1966";
UPDATE Films SET Distributor = "Janus Films" WHERE Title = "No More Excuses" AND Year = "1968";
UPDATE Films SET Distributor = "Janus Films" WHERE Title = "Two Tons of Turquoise to Taos Tonight" AND Year = "1975";
UPDATE Films SET Distributor = "Janus Films" WHERE Title = "Day of Wrath" AND Year = "1943";
UPDATE Films SET Distributor = "Janus Films" WHERE Title = "Gertrud" AND Year = "1964";
UPDATE Films SET Distributor = "Janus Films" WHERE Title = "Ordet" AND Year = "1955";
UPDATE Films SET Distributor = "Janus Films" WHERE Title = "The Passion of Joan of Arc" AND Year = "1928";
UPDATE Films SET Distributor = "Janus Films" WHERE Title = "Vampyr" AND Year = "1932";
UPDATE Films SET Distributor = "Janus Films" WHERE Title = "Master of the House" AND Year = "1925";
UPDATE Films SET Distributor = "Janus Films" WHERE Title = "Three Cases of Murder" AND Year = "1955";
UPDATE Films SET Distributor = "Janus Films" WHERE Title = "The Times of Harvey Milk" AND Year = "1984";
UPDATE Films SET Distributor = "Janus Films" WHERE Title = "The Spirit of the Beehive" AND Year = "1973";
UPDATE Films SET Distributor = "Janus Films" WHERE Title = "Bernard Shaw's Androcles and the Lion" AND Year = "1952";
UPDATE Films SET Distributor = "Janus Films" WHERE Title = "As Long as You've Got Your Health" AND Year = "1966";
UPDATE Films SET Distributor = "Janus Films" WHERE Title = "Feeling Good" AND Year = "1966";
UPDATE Films SET Distributor = "Janus Films" WHERE Title = "Le Grand Amour" AND Year = "1969";
UPDATE Films SET Distributor = "Janus Films" WHERE Title = "The Anniversary" AND Year = "1962";
UPDATE Films SET Distributor = "Janus Films" WHERE Title = "Land of Milk and Honey" AND Year = "1971";
UPDATE Films SET Distributor = "Janus Films" WHERE Title = "Rupture" AND Year = "1961";
UPDATE Films SET Distributor = "Janus Films" WHERE Title = "The Suitor" AND Year = "1963";
UPDATE Films SET Distributor = "Janus Films" WHERE Title = "Yoyo" AND Year = "1965";
UPDATE Films SET Distributor = "Janus Films" WHERE Title = "Katzelmacher" AND Year = "1969";
UPDATE Films SET Distributor = "Janus Films" WHERE Title = "Love is Colder Than Death" AND Year = "1969";
UPDATE Films SET Distributor = "Janus Films" WHERE Title = "The American Soldier" AND Year = "1970";
UPDATE Films SET Distributor = "Janus Films" WHERE Title = "Gods of the Plague" AND Year = "1970";
UPDATE Films SET Distributor = "Janus Films" WHERE Title = "Beware of a Holy Whore" AND Year = "1971";
UPDATE Films SET Distributor = "Janus Films" WHERE Title = "The Merchant of Four Seasons" AND Year = "1971";
UPDATE Films SET Distributor = "Janus Films" WHERE Title = "The Bitter Tears of Petra von Kant" AND Year = "1972";
UPDATE Films SET Distributor = "Janus Films" WHERE Title = "World on a Wire" AND Year = "1973";
UPDATE Films SET Distributor = "Janus Films" WHERE Title = "Fear Eats the Soul" AND Year = "1974";
UPDATE Films SET Distributor = "Janus Films" WHERE Title = "Effi Briest" AND Year = "1974";
UPDATE Films SET Distributor = "Janus Films" WHERE Title = "Fear of Fear" AND Year = "1975";
UPDATE Films SET Distributor = "Janus Films" WHERE Title = "Fox and His Friends" AND Year = "1975";
UPDATE Films SET Distributor = "Janus Films" WHERE Title = "Mother Kusters Goes to Heaven" AND Year = "1975";
UPDATE Films SET Distributor = "Janus Films" WHERE Title = "Chinese Roulette" AND Year = "1976";
UPDATE Films SET Distributor = "Janus Films" WHERE Title = "Satan's Brew" AND Year = "1976";
UPDATE Films SET Distributor = "Janus Films" WHERE Title = "The Marriage of Maria Braun" AND Year = "1979";
UPDATE Films SET Distributor = "Janus Films" WHERE Title = "Lola" AND Year = "1981";
UPDATE Films SET Distributor = "Janus Films" WHERE Title = "Veronika Voss" AND Year = "1982";
UPDATE Films SET Distributor = "Janus Films" WHERE Title = "8½" AND Year = "1963";
UPDATE Films SET Distributor = "Janus Films" WHERE Title = "Amarcord" AND Year = "1973";
UPDATE Films SET Distributor = "Janus Films" WHERE Title = "The Ship Sails On" AND Year = "1983";
UPDATE Films SET Distributor = "Janus Films" WHERE Title = "La Strada" AND Year = "1954";
UPDATE Films SET Distributor = "Janus Films" WHERE Title = "I Vitelloni" AND Year = "1953";
UPDATE Films SET Distributor = "Janus Films" WHERE Title = "Elephant Boy" AND Year = "1937";
UPDATE Films SET Distributor = "Janus Films" WHERE Title = "The Firemen's Ball" AND Year = "1967";
UPDATE Films SET Distributor = "Janus Films" WHERE Title = "The Loves of a Blonde" AND Year = "1965";
UPDATE Films SET Distributor = "Janus Films" WHERE Title = "Judex" AND Year = "1963";
UPDATE Films SET Distributor = "Janus Films" WHERE Title = "The Baron of Arizona" AND Year = "1950";
UPDATE Films SET Distributor = "Janus Films" WHERE Title = "I Shot Jesse James" AND Year = "1949";
UPDATE Films SET Distributor = "Janus Films" WHERE Title = "The Steel Helmet" AND Year = "1951";
UPDATE Films SET Distributor = "Janus Films" WHERE Title = "Cruel Gun Story" AND Year = "1964";
UPDATE Films SET Distributor = "Janus Films" WHERE Title = "Divorce Italian Style" AND Year = "1961";
UPDATE Films SET Distributor = "Janus Films" WHERE Title = "Seduced And Abandoned" AND Year = "1964";
UPDATE Films SET Distributor = "Janus Films" WHERE Title = "Just Great" AND Year = "1972";
UPDATE Films SET Distributor = "Janus Films" WHERE Title = "Vivre Sa Vie" AND Year = "1962";
UPDATE Films SET Distributor = "Janus Films" WHERE Title = "Weekend" AND Year = "1967";
UPDATE Films SET Distributor = "Janus Films" WHERE Title = "My Crasy Life" AND Year = "1992";
UPDATE Films SET Distributor = "Janus Films" WHERE Title = "Poto and Cabengo" AND Year = "1980";
UPDATE Films SET Distributor = "Janus Films" WHERE Title = "Routine Pleasures" AND Year = "1986";
UPDATE Films SET Distributor = "Janus Films" WHERE Title = "Kumokiri Nizaemon" AND Year = "1978";
UPDATE Films SET Distributor = "Janus Films" WHERE Title = "Sword of the Beast" AND Year = "1965";
UPDATE Films SET Distributor = "Janus Films" WHERE Title = "Three Outlaw Samurai" AND Year = "1964";
UPDATE Films SET Distributor = "Janus Films" WHERE Title = "Symbiopsychotaxiplasm Take 1" AND Year = "1968";
UPDATE Films SET Distributor = "Janus Films" WHERE Title = "George Washington" AND Year = "2000";
UPDATE Films SET Distributor = "Janus Films" WHERE Title = "The Woman Who Dared" AND Year = "1944";
UPDATE Films SET Distributor = "Janus Films" WHERE Title = "Lumière d'été" AND Year = "1943";
UPDATE Films SET Distributor = "Janus Films" WHERE Title = "Stormy Waters" AND Year = "1941";
UPDATE Films SET Distributor = "Janus Films" WHERE Title = "Désiré" AND Year = "1937";
UPDATE Films SET Distributor = "Janus Films" WHERE Title = "The Pearls of the Crown" AND Year = "1937";
UPDATE Films SET Distributor = "Janus Films" WHERE Title = "Quadrille" AND Year = "1938";
UPDATE Films SET Distributor = "Janus Films" WHERE Title = "The Story of a Cheat" AND Year = "1936";
UPDATE Films SET Distributor = "Janus Films" WHERE Title = "My Life as a Dog" AND Year = "1985";
UPDATE Films SET Distributor = "Janus Films" WHERE Title = "Under the Volcano" AND Year = "1984";
UPDATE Films SET Distributor = "Janus Films" WHERE Title = "Jhon Huston's Wise Blood" AND Year = "1979";
UPDATE Films SET Distributor = "Janus Films" WHERE Title = "The Burmese Harp" AND Year = "1956";
UPDATE Films SET Distributor = "Janus Films" WHERE Title = "Fires on the Plain" AND Year = "1959";
UPDATE Films SET Distributor = "Janus Films" WHERE Title = "The Makioka Sisters" AND Year = "1983";
UPDATE Films SET Distributor = "Janus Films" WHERE Title = "The Insect Woman" AND Year = "1963";
UPDATE Films SET Distributor = "Janus Films" WHERE Title = "Intentions of Murder" AND Year = "1964";
UPDATE Films SET Distributor = "Janus Films" WHERE Title = "Pigs & Battleships" AND Year = "1962";
UPDATE Films SET Distributor = "Janus Films" WHERE Title = "The Pornographers" AND Year = "1966";
UPDATE Films SET Distributor = "Janus Films" WHERE Title = "Vengeance is Mine" AND Year = "1979";
UPDATE Films SET Distributor = "Janus Films" WHERE Title = "Samurai I: Musashi Miyamoto" AND Year = "1954";
UPDATE Films SET Distributor = "Janus Films" WHERE Title = "Samurai II: Duel at Ichijoji Temple" AND Year = "1955";
UPDATE Films SET Distributor = "Janus Films" WHERE Title = "Samurai III: Duel at Ganryu Island" AND Year = "1956";
UPDATE Films SET Distributor = "Janus Films" WHERE Title = "Aru kengo no shogai" AND Year = "1959";
UPDATE Films SET Distributor = "Janus Films" WHERE Title = "Hoop Dreams" AND Year = "1994";
UPDATE Films SET Distributor = "Janus Films" WHERE Title = "Jubilee" AND Year = "1978";
UPDATE Films SET Distributor = "Janus Films" WHERE Title = "Down by Law" AND Year = "1986";
UPDATE Films SET Distributor = "Janus Films" WHERE Title = "Mystery Train" AND Year = "1990";
UPDATE Films SET Distributor = "Janus Films" WHERE Title = "Night on Earth" AND Year = "1991";
UPDATE Films SET Distributor = "Janus Films" WHERE Title = "Permanent Vacation" AND Year = "1980";
UPDATE Films SET Distributor = "Janus Films" WHERE Title = "Stranger Than Paradise" AND Year = "1984";
UPDATE Films SET Distributor = "Janus Films" WHERE Title = "The Joke" AND Year = "1969";
UPDATE Films SET Distributor = "Janus Films" WHERE Title = "The Shop on Main Street" AND Year = "1965";
UPDATE Films SET Distributor = "Janus Films" WHERE Title = "Honeymoon Killers" AND Year = "1970";
UPDATE Films SET Distributor = "Janus Films" WHERE Title = "Ariel" AND Year = "1988";
UPDATE Films SET Distributor = "Janus Films" WHERE Title = "Le Havre" AND Year = "2011";
UPDATE Films SET Distributor = "Janus Films" WHERE Title = "Leningrad Cowboys Go America" AND Year = "1989";
UPDATE Films SET Distributor = "Janus Films" WHERE Title = "Leningrad Cowboys Meet Moses" AND Year = "1994";
UPDATE Films SET Distributor = "Janus Films" WHERE Title = "The Match Factory Girl" AND Year = "1990";
UPDATE Films SET Distributor = "Janus Films" WHERE Title = "Shadows in Paradise" AND Year = "1986";
UPDATE Films SET Distributor = "Janus Films" WHERE Title = "Total Balalaika Show" AND Year = "1994";
UPDATE Films SET Distributor = "Janus Films" WHERE Title = "La Vie de Bohème" AND Year = "1992";
UPDATE Films SET Distributor = "Janus Films" WHERE Title = "Clean, Shaven" AND Year = "1994";
UPDATE Films SET Distributor = "Janus Films" WHERE Title = "Close-Up" AND Year = "1990";
UPDATE Films SET Distributor = "Janus Films" WHERE Title = "Taste of Cherry" AND Year = "1997";
UPDATE Films SET Distributor = "Janus Films" WHERE Title = "The Double Life of Veronique" AND Year = "1991";
UPDATE Films SET Distributor = "Janus Films" WHERE Title = "Three Colors: Blue" AND Year = "1993";
UPDATE Films SET Distributor = "Janus Films" WHERE Title = "Three Colors: Red" AND Year = "1994";
UPDATE Films SET Distributor = "Janus Films" WHERE Title = "Three Colors: White" AND Year = "1993";
UPDATE Films SET Distributor = "Janus Films" WHERE Title = "Ballad of Narayama" AND Year = "1958";
UPDATE Films SET Distributor = "Janus Films" WHERE Title = "Twenty-Four Eyes" AND Year = "1954";
UPDATE Films SET Distributor = "Janus Films" WHERE Title = "Gate of Hell" AND Year = "1953";
UPDATE Films SET Distributor = "Janus Films" WHERE Title = "Black River" AND Year = "1957";
UPDATE Films SET Distributor = "Janus Films" WHERE Title = "Harakiri" AND Year = "1962";
UPDATE Films SET Distributor = "Janus Films" WHERE Title = "The Human Condition II: Road to Eternity" AND Year = "1959";
UPDATE Films SET Distributor = "Janus Films" WHERE Title = "The Human Condition II: Road to Eternity" AND Year = "1959";
UPDATE Films SET Distributor = "Janus Films" WHERE Title = "The Human Condition III: A Soldier's Prayer" AND Year = "1961";
UPDATE Films SET Distributor = "Janus Films" WHERE Title = "I Will Buy You" AND Year = "1956";
UPDATE Films SET Distributor = "Janus Films" WHERE Title = "The Inheritance" AND Year = "1962";
UPDATE Films SET Distributor = "Janus Films" WHERE Title = "Kwaidan" AND Year = "1964";
UPDATE Films SET Distributor = "Janus Films" WHERE Title = "Samurai Rebellion" AND Year = "1967";
UPDATE Films SET Distributor = "Janus Films" WHERE Title = "Kabe atsuki heya" AND Year = "1956";
UPDATE Films SET Distributor = "Janus Films" WHERE Title = "The Private Life of Don Juan" AND Year = "1934";
UPDATE Films SET Distributor = "Janus Films" WHERE Title = "The Private Life of Henry VIII." AND Year = "1933";
UPDATE Films SET Distributor = "Janus Films" WHERE Title = "Rembrandt" AND Year = "1936";
UPDATE Films SET Distributor = "Janus Films" WHERE Title = "That Hamilton Woman" AND Year = "1941";
UPDATE Films SET Distributor = "Janus Films" WHERE Title = "Drums" AND Year = "1938";
UPDATE Films SET Distributor = "Janus Films" WHERE Title = "The Four Feathers" AND Year = "1939";
UPDATE Films SET Distributor = "Janus Films" WHERE Title = "The Jungle Book" AND Year = "1942";
UPDATE Films SET Distributor = "Janus Films" WHERE Title = "Sanders of the River" AND Year = "1935";
UPDATE Films SET Distributor = "Janus Films" WHERE Title = "Martha Graham: Dance On Film" AND Year = "1959";
UPDATE Films SET Distributor = "Janus Films" WHERE Title = "Black Sun" AND Year = "1964";
UPDATE Films SET Distributor = "Janus Films" WHERE Title = "I Am Waiting" AND Year = "1957";
UPDATE Films SET Distributor = "Janus Films" WHERE Title = "I Hate But Love" AND Year = "1962";
UPDATE Films SET Distributor = "Janus Films" WHERE Title = "Intimidation" AND Year = "1960";
UPDATE Films SET Distributor = "Janus Films" WHERE Title = "Thirst for Love" AND Year = "1967";
UPDATE Films SET Distributor = "Janus Films" WHERE Title = "The Warped Ones" AND Year = "1960";
UPDATE Films SET Distributor = "Janus Films" WHERE Title = "The Bad Sleep Well" AND Year = "1960";
UPDATE Films SET Distributor = "Janus Films" WHERE Title = "Dodes'ka-den" AND Year = "1970";
UPDATE Films SET Distributor = "Janus Films" WHERE Title = "Drunken Angel" AND Year = "1948";
UPDATE Films SET Distributor = "Janus Films" WHERE Title = "The Hidden Fortress" AND Year = "1958";
UPDATE Films SET Distributor = "Janus Films" WHERE Title = "High And Low" AND Year = "1963";
UPDATE Films SET Distributor = "Janus Films" WHERE Title = "I Live in Fear" AND Year = "1955";
UPDATE Films SET Distributor = "Janus Films" WHERE Title = "The Idiot" AND Year = "1951";
UPDATE Films SET Distributor = "Janus Films" WHERE Title = "Ikiru" AND Year = "1952";
UPDATE Films SET Distributor = "Janus Films" WHERE Title = "The Lower Depths" AND Year = "1957";
UPDATE Films SET Distributor = "Janus Films" WHERE Title = "The Men Who Tread on the Tiger's Tail" AND Year = "1945";
UPDATE Films SET Distributor = "Janus Films" WHERE Title = "The Most Beautiful" AND Year = "1944";
UPDATE Films SET Distributor = "Janus Films" WHERE Title = "No Regrets for Our Youth" AND Year = "1946";
UPDATE Films SET Distributor = "Janus Films" WHERE Title = "One Wonderful Sunday" AND Year = "1947";
UPDATE Films SET Distributor = "Janus Films" WHERE Title = "Rashomon" AND Year = "1950";
UPDATE Films SET Distributor = "Janus Films" WHERE Title = "Red Beard" AND Year = "1965";
UPDATE Films SET Distributor = "Janus Films" WHERE Title = "Sanjuro" AND Year = "1962";
UPDATE Films SET Distributor = "Janus Films" WHERE Title = "Sanshiro Sugata" AND Year = "1943";
UPDATE Films SET Distributor = "Janus Films" WHERE Title = "Sanshiro Sugata Part Two" AND Year = "1945";
UPDATE Films SET Distributor = "Janus Films" WHERE Title = "Scandal" AND Year = "1950";
UPDATE Films SET Distributor = "Janus Films" WHERE Title = "Seven Samurai" AND Year = "1954";
UPDATE Films SET Distributor = "Janus Films" WHERE Title = "Stray Dog" AND Year = "1949";
UPDATE Films SET Distributor = "Janus Films" WHERE Title = "Throne of Blood" AND Year = "1957";
UPDATE Films SET Distributor = "Janus Films" WHERE Title = "Yojimbo" AND Year = "1961";
UPDATE Films SET Distributor = "Janus Films" WHERE Title = "Cure" AND Year = "1997";
UPDATE Films SET Distributor = "Janus Films" WHERE Title = "The Red Balloon" AND Year = "1956";
UPDATE Films SET Distributor = "Janus Films" WHERE Title = "White Mane: The Wild Horse" AND Year = "1953";
UPDATE Films SET Distributor = "Janus Films" WHERE Title = "Hobson's Choice" AND Year = "1954";
UPDATE Films SET Distributor = "Janus Films" WHERE Title = "Summertime" AND Year = "1955";
UPDATE Films SET Distributor = "Janus Films" WHERE Title = "A Hard Day's Night" AND Year = "1964";
UPDATE Films SET Distributor = "Janus Films" WHERE Title = "The Freshman" AND Year = "1925";
UPDATE Films SET Distributor = "Janus Films" WHERE Title = "Safety Last!" AND Year = "1923";
UPDATE Films SET Distributor = "Janus Films" WHERE Title = "Innocence Unprotected" AND Year = "1968";
UPDATE Films SET Distributor = "Janus Films" WHERE Title = "Love Affair, or the Case of the Missing Switchboard Operator" AND Year = "1967";
UPDATE Films SET Distributor = "Janus Films" WHERE Title = "Man Is Not a Bird" AND Year = "1965";
UPDATE Films SET Distributor = "Janus Films" WHERE Title = "Sweet Movie" AND Year = "1974";
UPDATE Films SET Distributor = "Janus Films" WHERE Title = "WR: Mysteries of the Organism" AND Year = "1971";
UPDATE Films SET Distributor = "Janus Films" WHERE Title = "And The Pursuit Of Happiness" AND Year = "1986";
UPDATE Films SET Distributor = "Janus Films" WHERE Title = "Au Revoir Les Enfants" AND Year = "1987";
UPDATE Films SET Distributor = "Janus Films" WHERE Title = "Black Moon" AND Year = "1975";
UPDATE Films SET Distributor = "Janus Films" WHERE Title = "Calcutta" AND Year = "1969";
UPDATE Films SET Distributor = "Janus Films" WHERE Title = "The Fire Within" AND Year = "1963";
UPDATE Films SET Distributor = "Janus Films" WHERE Title = "God's Country" AND Year = "1985";
UPDATE Films SET Distributor = "Janus Films" WHERE Title = "Humain, trop humain" AND Year = "1973";
UPDATE Films SET Distributor = "Janus Films" WHERE Title = "Lacombe, Lucien" AND Year = "1974";
UPDATE Films SET Distributor = "Janus Films" WHERE Title = "The Lovers" AND Year = "1958";
UPDATE Films SET Distributor = "Janus Films" WHERE Title = "Milou in May" AND Year = "1990";
UPDATE Films SET Distributor = "Janus Films" WHERE Title = "Murmur of the Heart" AND Year = "1970";
UPDATE Films SET Distributor = "Janus Films" WHERE Title = "My Dinner with André" AND Year = "1981";
UPDATE Films SET Distributor = "Janus Films" WHERE Title = "Phantom India" AND Year = "1969";
UPDATE Films SET Distributor = "Janus Films" WHERE Title = "Place de la République" AND Year = "1974";
UPDATE Films SET Distributor = "Janus Films" WHERE Title = "Vive le tour" AND Year = "1962";
UPDATE Films SET Distributor = "Janus Films" WHERE Title = "Zazie dans le Metro" AND Year = "1960";
UPDATE Films SET Distributor = "Janus Films" WHERE Title = "La Jetée" AND Year = "1963";
UPDATE Films SET Distributor = "Janus Films" WHERE Title = "Sans Soleil" AND Year = "1983";
UPDATE Films SET Distributor = "Janus Films" WHERE Title = "Rusty Knife" AND Year = "1958";
UPDATE Films SET Distributor = "Janus Films" WHERE Title = "Chains" AND Year = "1949";
UPDATE Films SET Distributor = "Janus Films" WHERE Title = "Nobody's Children" AND Year = "1952";
UPDATE Films SET Distributor = "Janus Films" WHERE Title = "Torment" AND Year = "1950";
UPDATE Films SET Distributor = "Janus Films" WHERE Title = "The White Angel" AND Year = "1955";
UPDATE Films SET Distributor = "Janus Films" WHERE Title = "The Living Skeleton" AND Year = "1968";
UPDATE Films SET Distributor = "Janus Films" WHERE Title = "The Beales of Grey Gardens" AND Year = "2006";
UPDATE Films SET Distributor = "Janus Films" WHERE Title = "The Rolling Stones: Gimme Shelter" AND Year = "1970";
UPDATE Films SET Distributor = "Janus Films" WHERE Title = "Grey Gardens" AND Year = "1975";
UPDATE Films SET Distributor = "Janus Films" WHERE Title = "Salesman" AND Year = "1968";
UPDATE Films SET Distributor = "Janus Films" WHERE Title = "Le Deuxieme Souffle" AND Year = "1966";
UPDATE Films SET Distributor = "Janus Films" WHERE Title = "Le Samouraï" AND Year = "1967";
UPDATE Films SET Distributor = "Janus Films" WHERE Title = "Capricious Summer" AND Year = "1968";
UPDATE Films SET Distributor = "Janus Films" WHERE Title = "Closely Watched Trains" AND Year = "1966";
UPDATE Films SET Distributor = "Janus Films" WHERE Title = "Pearls of the Deep" AND Year = "1966";
UPDATE Films SET Distributor = "Janus Films" WHERE Title = "Things to Come" AND Year = "1936";
UPDATE Films SET Distributor = "Janus Films" WHERE Title = "The Life of Oharu" AND Year = "1952";
UPDATE Films SET Distributor = "Janus Films" WHERE Title = "Osaka Elegy" AND Year = "1936";
UPDATE Films SET Distributor = "Janus Films" WHERE Title = "Sansho Dayu" AND Year = "1954";
UPDATE Films SET Distributor = "Janus Films" WHERE Title = "Sisters of the Gion" AND Year = "1936";
UPDATE Films SET Distributor = "Janus Films" WHERE Title = "Street of Shame" AND Year = "1956";
UPDATE Films SET Distributor = "Janus Films" WHERE Title = "Ugetsu" AND Year = "1953";
UPDATE Films SET Distributor = "Janus Films" WHERE Title = "Utamaro and His Five Women" AND Year = "1946";
UPDATE Films SET Distributor = "Janus Films" WHERE Title = "Women of the Night" AND Year = "1948";
UPDATE Films SET Distributor = "Janus Films" WHERE Title = "The Organiser" AND Year = "1963";
UPDATE Films SET Distributor = "Janus Films" WHERE Title = "The Sinners of Hell" AND Year = "1960";
UPDATE Films SET Distributor = "Janus Films" WHERE Title = "Crazed Fruit" AND Year = "1956";
UPDATE Films SET Distributor = "Janus Films" WHERE Title = "Apart from You" AND Year = "1933";
UPDATE Films SET Distributor = "Janus Films" WHERE Title = "Nightfly Dreams" AND Year = "1933";
UPDATE Films SET Distributor = "Janus Films" WHERE Title = "Flunky, Work Hard!" AND Year = "1931";
UPDATE Films SET Distributor = "Janus Films" WHERE Title = "No Blood Relation" AND Year = "1932";
UPDATE Films SET Distributor = "Janus Films" WHERE Title = "Street Without End" AND Year = "1934";
UPDATE Films SET Distributor = "Janus Films" WHERE Title = "When a Woman Ascends the Stairs" AND Year = "1960";
UPDATE Films SET Distributor = "Janus Films" WHERE Title = "The North" AND Year = "1983";
UPDATE Films SET Distributor = "Janus Films" WHERE Title = "The Horse's Mouth" AND Year = "1958";
UPDATE Films SET Distributor = "Janus Films" WHERE Title = "Tunes of Glory" AND Year = "1960";
UPDATE Films SET Distributor = "Janus Films" WHERE Title = "The Party and the Guests" AND Year = "1966";
UPDATE Films SET Distributor = "Janus Films" WHERE Title = "Genocide" AND Year = "1968";
UPDATE Films SET Distributor = "Janus Films" WHERE Title = "The X from Outer Space" AND Year = "1967";
UPDATE Films SET Distributor = "Janus Films" WHERE Title = "A Colt Is My Passport" AND Year = "1967";
UPDATE Films SET Distributor = "Janus Films" WHERE Title = "House: The Director's Cut Edition" AND Year = "1977";
UPDATE Films SET Distributor = "Janus Films" WHERE Title = "Kill!" AND Year = "1968";
UPDATE Films SET Distributor = "Janus Films" WHERE Title = "The Sword of Doom" AND Year = "1966";
UPDATE Films SET Distributor = "Janus Films" WHERE Title = "Richard III" AND Year = "1955";
UPDATE Films SET Distributor = "Janus Films" WHERE Title = "The Fiances" AND Year = "1962";
UPDATE Films SET Distributor = "Janus Films" WHERE Title = "Il Posto" AND Year = "1961";
UPDATE Films SET Distributor = "Janus Films" WHERE Title = "The Earrings of Madame De..." AND Year = "1953";
UPDATE Films SET Distributor = "Janus Films" WHERE Title = "Le Plaisir" AND Year = "1952";
UPDATE Films SET Distributor = "Janus Films" WHERE Title = "La Ronde" AND Year = "1950";
UPDATE Films SET Distributor = "Janus Films" WHERE Title = "Boy" AND Year = "1969";
UPDATE Films SET Distributor = "Janus Films" WHERE Title = "The Ceremony" AND Year = "1971";
UPDATE Films SET Distributor = "Janus Films" WHERE Title = "Death by Hanging" AND Year = "1968";
UPDATE Films SET Distributor = "Janus Films" WHERE Title = "Empire of Passion" AND Year = "1978";
UPDATE Films SET Distributor = "Janus Films" WHERE Title = "In the Realm of the Senses" AND Year = "1976";
UPDATE Films SET Distributor = "Janus Films" WHERE Title = "Japanese Summer: Unreasonable Double Suicide" AND Year = "1967";
UPDATE Films SET Distributor = "Janus Films" WHERE Title = "The Man Who Left His Will on Film" AND Year = "1970";
UPDATE Films SET Distributor = "Janus Films" WHERE Title = "Merry Christmas, Mr. Lawrence" AND Year = "1983";
UPDATE Films SET Distributor = "Janus Films" WHERE Title = "Pleasures of the Flesh" AND Year = "1965";
UPDATE Films SET Distributor = "Janus Films" WHERE Title = "Sing a Song of Sex" AND Year = "1967";
UPDATE Films SET Distributor = "Janus Films" WHERE Title = "Three Resurrected Drunkards" AND Year = "1968";
UPDATE Films SET Distributor = "Janus Films" WHERE Title = "Violence at Noon" AND Year = "1966";
UPDATE Films SET Distributor = "Janus Films" WHERE Title = "Days of Youth" AND Year = "1929";
UPDATE Films SET Distributor = "Janus Films" WHERE Title = "I Passed But..." AND Year = "1929";
UPDATE Films SET Distributor = "Janus Films" WHERE Title = "The Charging Kid" AND Year = "1929";
UPDATE Films SET Distributor = "Janus Films" WHERE Title = "I Flunked, But..." AND Year = "1930";
UPDATE Films SET Distributor = "Janus Films" WHERE Title = "That Night's Wife" AND Year = "1930";
UPDATE Films SET Distributor = "Janus Films" WHERE Title = "Walk Cheerfully" AND Year = "1930";
UPDATE Films SET Distributor = "Janus Films" WHERE Title = "The Lady and the Beard" AND Year = "1931";
UPDATE Films SET Distributor = "Janus Films" WHERE Title = "Tokyo Chorus" AND Year = "1931";
UPDATE Films SET Distributor = "Janus Films" WHERE Title = "I Was Born, But..." AND Year = "1932";
UPDATE Films SET Distributor = "Janus Films" WHERE Title = "Where Now Are the Dreams of Youth" AND Year = "1932";
UPDATE Films SET Distributor = "Janus Films" WHERE Title = "Dragnet Girl" AND Year = "1933";
UPDATE Films SET Distributor = "Janus Films" WHERE Title = "Passing Fancy" AND Year = "1933";
UPDATE Films SET Distributor = "Janus Films" WHERE Title = "Woman of Tokyo" AND Year = "1933";
UPDATE Films SET Distributor = "Janus Films" WHERE Title = "A Mother Should Be Loved" AND Year = "1934";
UPDATE Films SET Distributor = "Janus Films" WHERE Title = "A Story of Floating Weeds" AND Year = "1934";
UPDATE Films SET Distributor = "Janus Films" WHERE Title = "An Inn in Tokyo" AND Year = "1935";
UPDATE Films SET Distributor = "Janus Films" WHERE Title = "The Only Son" AND Year = "1936";
UPDATE Films SET Distributor = "Janus Films" WHERE Title = "What Did the Lady Forget?" AND Year = "1937";
UPDATE Films SET Distributor = "Janus Films" WHERE Title = "The Brothers and Sisters of the Toda Family" AND Year = "1941";
UPDATE Films SET Distributor = "Janus Films" WHERE Title = "There Was a Father" AND Year = "1942";
UPDATE Films SET Distributor = "Janus Films" WHERE Title = "Record of a Tenement Gentleman" AND Year = "1947";
UPDATE Films SET Distributor = "Janus Films" WHERE Title = "A Hen in the Wind" AND Year = "1948";
UPDATE Films SET Distributor = "Janus Films" WHERE Title = "Late Spring" AND Year = "1949";
UPDATE Films SET Distributor = "Janus Films" WHERE Title = "Early Summer" AND Year = "1951";
UPDATE Films SET Distributor = "Janus Films" WHERE Title = "Flavor of Green Tea Over Rice" AND Year = "1952";
UPDATE Films SET Distributor = "Janus Films" WHERE Title = "Tokyo Story" AND Year = "1953";
UPDATE Films SET Distributor = "Janus Films" WHERE Title = "Early Spring" AND Year = "1956";
UPDATE Films SET Distributor = "Janus Films" WHERE Title = "Tokyo Twilight" AND Year = "1957";
UPDATE Films SET Distributor = "Janus Films" WHERE Title = "Equinox Flower" AND Year = "1958";
UPDATE Films SET Distributor = "Janus Films" WHERE Title = "Floating Weeds" AND Year = "1959";
UPDATE Films SET Distributor = "Janus Films" WHERE Title = "Good Morning" AND Year = "1959";
UPDATE Films SET Distributor = "Janus Films" WHERE Title = "Late Autumn" AND Year = "1960";
UPDATE Films SET Distributor = "Janus Films" WHERE Title = "The End of Summer" AND Year = "1961";
UPDATE Films SET Distributor = "Janus Films" WHERE Title = "An Autumn Afternoon" AND Year = "1962";
UPDATE Films SET Distributor = "Janus Films" WHERE Title = "Major Barbara" AND Year = "1941";
UPDATE Films SET Distributor = "Janus Films" WHERE Title = "Mamma Roma" AND Year = "1962";
UPDATE Films SET Distributor = "Janus Films" WHERE Title = "To Our Loves" AND Year = "1983";
UPDATE Films SET Distributor = "Janus Films" WHERE Title = "Naked Childhood" AND Year = "1968";
UPDATE Films SET Distributor = "Janus Films" WHERE Title = "The Most Dangerous Game" AND Year = "1932";
UPDATE Films SET Distributor = "Janus Films" WHERE Title = "Break Up the Dance" AND Year = "1957";
UPDATE Films SET Distributor = "Janus Films" WHERE Title = "Knife in the Water" AND Year = "1962";
UPDATE Films SET Distributor = "Janus Films" WHERE Title = "The Lamp" AND Year = "1959";
UPDATE Films SET Distributor = "Janus Films" WHERE Title = "Mammals" AND Year = "1962";
UPDATE Films SET Distributor = "Janus Films" WHERE Title = "Murder" AND Year = "1957";
UPDATE Films SET Distributor = "Janus Films" WHERE Title = "Teeth Smile" AND Year = "1957";
UPDATE Films SET Distributor = "Janus Films" WHERE Title = "Tess" AND Year = "1979";
UPDATE Films SET Distributor = "Janus Films" WHERE Title = "Two Men and a Wardrobe" AND Year = "1958";
UPDATE Films SET Distributor = "Janus Films" WHERE Title = "When Angels Fall" AND Year = "1959";
UPDATE Films SET Distributor = "Janus Films" WHERE Title = "Kapò" AND Year = "1959";
UPDATE Films SET Distributor = "Janus Films" WHERE Title = "The Big City: Mahanagar" AND Year = "1963";
UPDATE Films SET Distributor = "Janus Films" WHERE Title = "Charulata" AND Year = "1964";
UPDATE Films SET Distributor = "Janus Films" WHERE Title = "An Enemy of the People" AND Year = "1989";
UPDATE Films SET Distributor = "Janus Films" WHERE Title = "The Home and the World" AND Year = "1984";
UPDATE Films SET Distributor = "Janus Films" WHERE Title = "The Music Room" AND Year = "1958";
UPDATE Films SET Distributor = "Janus Films" WHERE Title = "The Stranger" AND Year = "1991";
UPDATE Films SET Distributor = "Janus Films" WHERE Title = "For All Mankind" AND Year = "1989";
UPDATE Films SET Distributor = "Janus Films" WHERE Title = "La Bête Humaine" AND Year = "1938";
UPDATE Films SET Distributor = "Janus Films" WHERE Title = "Boudu Saved From Drowning" AND Year = "1932";
UPDATE Films SET Distributor = "Janus Films" WHERE Title = "Elena and Her Men" AND Year = "1956";
UPDATE Films SET Distributor = "Janus Films" WHERE Title = "Only the French Can" AND Year = "1954";
UPDATE Films SET Distributor = "Janus Films" WHERE Title = "The Golden Coach" AND Year = "1952";
UPDATE Films SET Distributor = "Janus Films" WHERE Title = "The River" AND Year = "1951";
UPDATE Films SET Distributor = "Janus Films" WHERE Title = "The Rules of the Game" AND Year = "1939";
UPDATE Films SET Distributor = "Janus Films" WHERE Title = "Evening Classes" AND Year = "1967";
UPDATE Films SET Distributor = "Janus Films" WHERE Title = "Il Sorpasso" AND Year = "1962";
UPDATE Films SET Distributor = "Janus Films" WHERE Title = "Walkabout" AND Year = "1971";
UPDATE Films SET Distributor = "Janus Films" WHERE Title = "Claire's Knee" AND Year = "1970";
UPDATE Films SET Distributor = "Janus Films" WHERE Title = "The Collector" AND Year = "1967";
UPDATE Films SET Distributor = "Janus Films" WHERE Title = "My Night at Maud's" AND Year = "1969";
UPDATE Films SET Distributor = "Janus Films" WHERE Title = "Suzanne's Career" AND Year = "1963";
UPDATE Films SET Distributor = "Janus Films" WHERE Title = "Hands Over the City" AND Year = "1963";
UPDATE Films SET Distributor = "Janus Films" WHERE Title = "The Moment of Truth" AND Year = "1965";
UPDATE Films SET Distributor = "Janus Films" WHERE Title = "Salvatore Giuliano" AND Year = "1962";
UPDATE Films SET Distributor = "Janus Films" WHERE Title = "The Age of the Medici" AND Year = "1973";
UPDATE Films SET Distributor = "Janus Films" WHERE Title = "Blaise Pascal" AND Year = "1972";
UPDATE Films SET Distributor = "Janus Films" WHERE Title = "Cartesius" AND Year = "1974";
UPDATE Films SET Distributor = "Janus Films" WHERE Title = "Europe '51" AND Year = "1952";
UPDATE Films SET Distributor = "Janus Films" WHERE Title = "The Flowers of St. Francis" AND Year = "1950";
UPDATE Films SET Distributor = "Janus Films" WHERE Title = "Germany Year Zero" AND Year = "1948";
UPDATE Films SET Distributor = "Janus Films" WHERE Title = "Journey to Italy" AND Year = "1954";
UPDATE Films SET Distributor = "Janus Films" WHERE Title = "Paisan" AND Year = "1946";
UPDATE Films SET Distributor = "Janus Films" WHERE Title = "Rome, Open City" AND Year = "1945";
UPDATE Films SET Distributor = "Janus Films" WHERE Title = "Stromboli" AND Year = "1950";
UPDATE Films SET Distributor = "Janus Films" WHERE Title = "The Taking of Power By Louis XIV" AND Year = "1966";
UPDATE Films SET Distributor = "Janus Films" WHERE Title = "Chronicle of a Summer" AND Year = "1961";
UPDATE Films SET Distributor = "Janus Films" WHERE Title = "Maedchen in Uniform" AND Year = "1931";
UPDATE Films SET Distributor = "Janus Films" WHERE Title = "Goke, Body Snatcher from Hell" AND Year = "1968";
UPDATE Films SET Distributor = "Janus Films" WHERE Title = "Cria Cuervos" AND Year = "1976";
UPDATE Films SET Distributor = "Janus Films" WHERE Title = "Coup de grâce" AND Year = "1976";
UPDATE Films SET Distributor = "Janus Films" WHERE Title = "The Tin Drum" AND Year = "1979";
UPDATE Films SET Distributor = "Janus Films" WHERE Title = "Young Torless" AND Year = "1966";
UPDATE Films SET Distributor = "Janus Films" WHERE Title = "The Return of the Prodigal Son" AND Year = "1967";
UPDATE Films SET Distributor = "Janus Films" WHERE Title = "The Lost Honor of Katharina Blum" AND Year = "1975";
UPDATE Films SET Distributor = "Janus Films" WHERE Title = "Japanese Girls at the Harbor" AND Year = "1933";
UPDATE Films SET Distributor = "Janus Films" WHERE Title = "The Masseurs and a Woman" AND Year = "1938";
UPDATE Films SET Distributor = "Janus Films" WHERE Title = "Mr. Thank You" AND Year = "1936";
UPDATE Films SET Distributor = "Janus Films" WHERE Title = "Ornamental Hairpin" AND Year = "1941";
UPDATE Films SET Distributor = "Janus Films" WHERE Title = "A Black Cat in a Bamboo Grove" AND Year = "1968";
UPDATE Films SET Distributor = "Janus Films" WHERE Title = "The Naked Island" AND Year = "1960";
UPDATE Films SET Distributor = "Janus Films" WHERE Title = "Onibaba" AND Year = "1964";
UPDATE Films SET Distributor = "Janus Films" WHERE Title = "Double Suicide" AND Year = "1969";
UPDATE Films SET Distributor = "Janus Films" WHERE Title = "Pale Flower" AND Year = "1964";
UPDATE Films SET Distributor = "Janus Films" WHERE Title = "Samurai Spy" AND Year = "1965";
UPDATE Films SET Distributor = "Janus Films" WHERE Title = "People on Sunday" AND Year = "1930";
UPDATE Films SET Distributor = "Janus Films" WHERE Title = "Torment" AND Year = "1944";
UPDATE Films SET Distributor = "Janus Films" WHERE Title = "Miss Julie" AND Year = "1951";
UPDATE Films SET Distributor = "Janus Films" WHERE Title = "I Am Curious" AND Year = "1968";
UPDATE Films SET Distributor = "Janus Films" WHERE Title = "I Am Curious" AND Year = "1967";
UPDATE Films SET Distributor = "Janus Films" WHERE Title = "The Phantom Carriage" AND Year = "1921";
UPDATE Films SET Distributor = "Janus Films" WHERE Title = "The Vanishing" AND Year = "1993";
UPDATE Films SET Distributor = "Janus Films" WHERE Title = "The Great Beauty" AND Year = "2013";
UPDATE Films SET Distributor = "Janus Films" WHERE Title = "Revanche" AND Year = "2008";
UPDATE Films SET Distributor = "Janus Films" WHERE Title = "Branded to Kill" AND Year = "1967";
UPDATE Films SET Distributor = "Janus Films" WHERE Title = "Fighting Elegy" AND Year = "1966";
UPDATE Films SET Distributor = "Janus Films" WHERE Title = "Gate of Flesh" AND Year = "1964";
UPDATE Films SET Distributor = "Janus Films" WHERE Title = "Story of a Prostitute" AND Year = "1965";
UPDATE Films SET Distributor = "Janus Films" WHERE Title = "Take Aim at the Police Van" AND Year = "1960";
UPDATE Films SET Distributor = "Janus Films" WHERE Title = "Tokyo Drifter" AND Year = "1966";
UPDATE Films SET Distributor = "Janus Films" WHERE Title = "Youth of the Beast" AND Year = "1963";
UPDATE Films SET Distributor = "Janus Films" WHERE Title = "Zatoichi: The Blind Swordsman's Return" AND Year = "1963";
UPDATE Films SET Distributor = "Janus Films" WHERE Title = "Zatoichi the Fugitive" AND Year = "1963";
UPDATE Films SET Distributor = "Janus Films" WHERE Title = "The Tunnel" AND Year = "1940";
UPDATE Films SET Distributor = "Janus Films" WHERE Title = "Antonio Gaudí" AND Year = "1985";
UPDATE Films SET Distributor = "Janus Films" WHERE Title = "The Face of Another" AND Year = "1966";
UPDATE Films SET Distributor = "Janus Films" WHERE Title = "Pitfall" AND Year = "1962";
UPDATE Films SET Distributor = "Janus Films" WHERE Title = "Woman of the Dunes" AND Year = "1964";
UPDATE Films SET Distributor = "Janus Films" WHERE Title = "The 400 Blows" AND Year = "1959";
UPDATE Films SET Distributor = "Janus Films" WHERE Title = "Antoine and Colette" AND Year = "1962";
UPDATE Films SET Distributor = "Janus Films" WHERE Title = "Bed & Board" AND Year = "1970";
UPDATE Films SET Distributor = "Janus Films" WHERE Title = "Finally, Sunday!" AND Year = "1983";
UPDATE Films SET Distributor = "Janus Films" WHERE Title = "Jules and Jim" AND Year = "1962";
UPDATE Films SET Distributor = "Janus Films" WHERE Title = "The Last Metro" AND Year = "1980";
UPDATE Films SET Distributor = "Janus Films" WHERE Title = "Love on the Run" AND Year = "1979";
UPDATE Films SET Distributor = "Janus Films" WHERE Title = "The Mischief Makers" AND Year = "1957";
UPDATE Films SET Distributor = "Janus Films" WHERE Title = "Shoot the Piano Player" AND Year = "1960";
UPDATE Films SET Distributor = "Janus Films" WHERE Title = "The Soft Skin" AND Year = "1964";
UPDATE Films SET Distributor = "Janus Films" WHERE Title = "Stolen Kisses" AND Year = "1968";
UPDATE Films SET Distributor = "Janus Films" WHERE Title = "Two English Girls" AND Year = "1971";
UPDATE Films SET Distributor = "Janus Films" WHERE Title = "The Woman Next Door" AND Year = "1981";
UPDATE Films SET Distributor = "Janus Films" WHERE Title = "The Love Goddesses: A History of Sex in the Cinema" AND Year = "1965";
UPDATE Films SET Distributor = "Janus Films" WHERE Title = "Paul Robeson: Tribute to an Artist" AND Year = "1979";
UPDATE Films SET Distributor = "Janus Films" WHERE Title = "Bad Night" AND Year = "1986";
UPDATE Films SET Distributor = "Janus Films" WHERE Title = "Le Bonheur" AND Year = "1965";
UPDATE Films SET Distributor = "Janus Films" WHERE Title = "Cleo from 5 to 7" AND Year = "1962";
UPDATE Films SET Distributor = "Janus Films" WHERE Title = "La Pointe Courte" AND Year = "1955";
UPDATE Films SET Distributor = "Janus Films" WHERE Title = "Vagabond" AND Year = "1985";
UPDATE Films SET Distributor = "Janus Films" WHERE Title = "The World of Jacques Demy" AND Year = "1995";
UPDATE Films SET Distributor = "Janus Films" WHERE Title = "À Propos de Nice" AND Year = "1933";
UPDATE Films SET Distributor = "Janus Films" WHERE Title = "L'Atalante" AND Year = "1934";
UPDATE Films SET Distributor = "Janus Films" WHERE Title = "Taris" AND Year = "1931";
UPDATE Films SET Distributor = "Janus Films" WHERE Title = "Zero de Conduite" AND Year = "1933";
UPDATE Films SET Distributor = "Janus Films" WHERE Title = "Le Notti Bianche" AND Year = "1957";
UPDATE Films SET Distributor = "Janus Films" WHERE Title = "Marketa Lazarova" AND Year = "1967";
UPDATE Films SET Distributor = "Janus Films" WHERE Title = "Breaking the Waves" AND Year = "1996";
UPDATE Films SET Distributor = "Janus Films" WHERE Title = "The Element of Crime" AND Year = "1984";
UPDATE Films SET Distributor = "Janus Films" WHERE Title = "Europa" AND Year = "1991";
UPDATE Films SET Distributor = "Janus Films" WHERE Title = "Border Radio" AND Year = "1987";
UPDATE Films SET Distributor = "Janus Films" WHERE Title = "Ashes And Diamonds" AND Year = "1958";
UPDATE Films SET Distributor = "Janus Films" WHERE Title = "Danton" AND Year = "1983";
UPDATE Films SET Distributor = "Janus Films" WHERE Title = "A Generation" AND Year = "1955";
UPDATE Films SET Distributor = "Janus Films" WHERE Title = "Kanal" AND Year = "1957";
UPDATE Films SET Distributor = "Janus Films" WHERE Title = "The Last Wave" AND Year = "1977";
UPDATE Films SET Distributor = "Janus Films" WHERE Title = "Picnic at Hanging Rock" AND Year = "1975";
UPDATE Films SET Distributor = "Janus Films" WHERE Title = "Mr. Arkadin" AND Year = "1955";
UPDATE Films SET Distributor = "Janus Films" WHERE Title = "F for Fake" AND Year = "1973";
UPDATE Films SET Distributor = "Janus Films" WHERE Title = "Paris, Texas" AND Year = "1984";
UPDATE Films SET Distributor = "Janus Films" WHERE Title = "Wings of Desire" AND Year = "1987";
UPDATE Films SET Distributor = "Janus Films" WHERE Title = "Zatoichi on the Road" AND Year = "1963";
UPDATE Films SET Distributor = "Janus Films" WHERE Title = "Louie Bluie" AND Year = "1985";
UPDATE Films SET Distributor = "Park Circus" WHERE Title = "Stella Dallas" AND Year = "1925";
UPDATE Films SET Distributor = "Park Circus" WHERE Title = "Stella Dallas" AND Year = "1937";
UPDATE Films SET Distributor = "Public Domain" WHERE Title = "Of Human Bondage" AND Year = "1934";
UPDATE Films SET Distributor = "Park Circus" WHERE Title = "The Little Foxes" AND Year = "1941";
UPDATE Films SET Distributor = "Swank" WHERE Title = "The Whales of August" AND Year = "1987";
UPDATE Films SET Distributor = "Swank", IMDb_Distributor = "Paramount" WHERE Title = "To Catch a Thief" AND Year = "1955";
UPDATE Films SET Distributor = "Swank" WHERE Title = "The 39 Steps" AND Year = "1935";
UPDATE Films SET Distributor = "Swank" WHERE Title = "Rio Lobo" AND Year = "1970";
UPDATE Films SET Distributor = "The Film Desk" WHERE Title = "The Devil, Probably" AND Year = "1977";
UPDATE Films SET Distributor = "The Film Desk" WHERE Title = "Promised Lands" AND Year = "1974";
UPDATE Films SET Distributor = "The Film Desk" WHERE Title = "The Long Day Closes" AND Year = "1992";
UPDATE Films SET Distributor = "The Film Desk" WHERE Title = "Trouble Every Day" AND Year = "2001";
UPDATE Films SET Runtime = "70" WHERE Title = "I Passed But..." AND Year = "1929";
UPDATE People SET Name = "Charlie Chaplin" WHERE Name = "Charles Chaplin";
UPDATE People SET Name = "Carl Dreyer" WHERE Name = "Carl Theodor Dreyer";
UPDATE Films SET Title = "L'Eclisse" WHERE Title = "Eclipse" and Year = 1962;
UPDATE Films SET Title = "Children of Paradise" WHERE Title = "Les Enfants du Paradis" and Year = 1945;
UPDATE Films SET Title = "The Great Dictator" WHERE Title = "The Dictator" and Year = 1940;
UPDATE Films SET Title = "Purple Noon" WHERE Title = "Plein Soleil" and Year = 1960;
UPDATE Films SET Title = "Ali: Fear Eats the Soul" WHERE Title = "Fear Eats the Soul" and Year = 1974;
UPDATE Films SET Title = "Tout Va Bien" WHERE Title = "Just Great" and Year = 1972;
UPDATE Films SET Title = "Bandits Vs. Samurai Squadron" WHERE Title = "Kumokiri Nizaemon" and Year = 1978;
UPDATE Films SET Title = "Wise Blood" WHERE Title = "Jhon Huston's Wise Blood" and Year = 1979;
UPDATE Films SET Title = "The Thick-Walled Room" WHERE Title = "Kabe atsuki heya" and Year = 1956;
UPDATE Films SET Title = "Hausu" WHERE Title = "House: The Director's Cut Edition" and Year = "1977";
UPDATE Films SET Title = "Japanese Summer: Double Suicide" WHERE Title = "Japanese Summer: Unreasonable Double Suicide" and Year = 1967;
UPDATE Films SET Title = "A Straightforward Boy" WHERE Title = "The Charging Kid" and Year = 1929;
UPDATE Films SET Title = "The Private Life of Henry VIII" WHERE Title = "The Private Life of Henry VIII." and Year = 1933;
UPDATE Films SET Title = "I Am Curious (Blue)" WHERE Title = "I Am Curious" and Year = 1968;
UPDATE Films SET Title = "I Am Curious (Yellow)" WHERE Title = "I Am Curious" and Year = 1967;
UPDATE Films SET Title = "New Tale of Zatoichi" WHERE Title = "Zatoichi: The Blind Swordsman's Return" and Year = 1963;
UPDATE Films SET Title = "Confidentally Yours" WHERE Title = "Finally, Sunday!" and Year = 1983;
UPDATE Films SET Distributor = "Janus Films" WHERE Title LIKE "%Zatoichi%" and Year < 1974;
INSERT INTO Directs VALUES ((SELECT Person_ID FROM People WHERE Name = "Harold Lloyd"), (SELECT Film_ID FROM Films WHERE Title = "The Freshman" and Year = 1925));
INSERT INTO Directs VALUES ((SELECT Person_ID FROM People WHERE Name = "Harold Lloyd"), (SELECT Film_ID FROM Films WHERE Title = "Safety Last!" and Year = 1923));
EOF
